# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.initrd.luks.devices."cryptroot" = {
    device = "/dev/disk/by-uuid/33c42a68-4334-4529-8670-82286cc0cb79";
    preLVM = true;
    allowDiscards = true;
  };

  boot.initrd.services.lvm.enable = true;

  boot = {
    extraModulePackages = [ ];
    blacklistedKernelModules = [ "nouveau" "snd_hda_intel" ]; # Example modules to blacklist
    kernelModules = [ "kvm-intel" ];
    kernelParams = [ "reboot=pci" "intel_pstate=active" "resume=UUID=33dad16f-250c-4993-b84b-05f69e978bb2" ];
  };

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/9a3e5059-0e6f-439b-ae7d-95286cfd95da";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/3263-A9F1";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/33dad16f-250c-4993-b84b-05f69e978bb2"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  # high-resolution display
  # hardware.video.hidpi.enable = lib.mkDefault true;
  services.fstrim.enable = lib.mkDefault true;
}
